version: '3'

services:
  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - sqlite_data:/data
    environment:
      DATABASE_URL: "sqlite:////data/database.db"
    depends_on:
      - db
    
  db:
    build:
      context: ./data
      dockerfile: Dockerfile
    volumes:
      - sqlite_data:/data

volumes:
  sqlite_data:
    driver: local
